#pragma once

#include "hlsl_cpp.hlsli"

FB_NAMESPACE_BEGIN

FB_CONSTANT uint LIGHT_COUNT = 32;
FB_CONSTANT uint SIM_DISPATCH_SIZE = 32;
FB_CONSTANT uint CULL_TILE_SIZE = 16;
FB_CONSTANT uint CULL_DISPATCH_SIZE = 16;
FB_CONSTANT float PLANE_RADIUS_X = 2.0f;
FB_CONSTANT float PLANE_RADIUS_Y = 1.0f;

FB_NAMESPACE_END
